### ISSUE TITLE
App Optimisations

### ISSUE THREAD

**Issue by adityag1998** [adityag1998/SmartNotes#1]
Clause : 
Dual Check on checking Android Version and Settings overlay permission grant is redundant

Check 1 : Before sending intent to OverlayPermissionActivity in ObjectNameReceiver.java
Check 2 : In OverlayPermissionActivity.java itself

Fix:
- [ ] Dual check of Overlay Setting Permission

**Comment by ArshiyanAlam** [comment]
done / unnecessary
