### ISSUE TITLE
UI Fix

### ISSUE THREAD

**Issue by adityag1998** [adityag1998/SmartNotes#3]
Problem :
1. Long Pressing Tag Simply deletes it.
2. It is possible that I must have long clicked accidentally on these small tags

Solution :
- [x] Implement Dialogue Interface warning

Help:
You can see implementation in normal notes deletion on long click in MainActivity for actual notes

**Comment by kuabhishek123** [comment]
Added Dialogue Interface warning with Yes, No selection. Pushed latest changes.
