### ISSUE TITLE
Sync with DummyCamera/ NaviCam

### ISSUE THREAD

**Issue by adityag1998** [adityag1998/SmartNotes#7]
1. DummyCamera has been updated to send bundle (Object List, String Text) instead of String ObjectName.
2. Action Name, Keys Name have been changed.

Do Following :
- [x] Update AndoidManifest.xml with setAction as com.samsung.navicam.parse_bundle
- [x] Fetch bundle using getBundle or getSerialzable and make sure to check name of keys in code of DummyCamera

**Comment by adityag1998** [comment]
1. A newer version of NaviCam has been pushed where it has been renamed Samsung Camera
2. In that key name to fetch bundle blockwiseTextString has been changed as follows:
const val KEY2 = "com.samsung.navicam.blockWiseTextList"
earlier (const val KEY2 = "com.samsung.navicam.text")
3. The type is again a string array where each string represents text in each block

Do Following :
- [x] Change key name when parsing bundle
- [x] Handle ArrayList<String> of blockwise text instead of String text earlier

**Comment by kuabhishek123** [comment]
Everything done.
